### ISSUE TITLE
Can't resolve baseline due to multiple file choices

### ISSUE THREAD

**Issue by aalmiray** [melix/japicmp-gradle-plugin#1]
Configuring the following block

```
task japicmp(type: me.champeau.gradle.ArtifactJapicmpTask) {
    baseline = 'org.codehaus.griffon:griffon-core:2.0.0'
    to = jar.archivePath
    onlyModified = true
    failOnModification = true
    txtOutputFile = file("$buildDir/reports/japicmp.txt")
}
```

leads to this exception

```
Caused by: java.lang.IllegalStateException: Expected configuration 'detachedConfiguration1' to contain exactly one file, however, it contains 4 files.
    at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:54)
    at me.champeau.gradle.ArtifactJapicmpTask.computeDependency(ArtifactJapicmpTask.groovy:61)
    at me.champeau.gradle.ArtifactJapicmpTask.this$4$computeDependency(ArtifactJapicmpTask.groovy)
    at me.champeau.gradle.ArtifactJapicmpTask$this$4$computeDependency.callCurrent(Unknown Source)
    at me.champeau.gradle.ArtifactJapicmpTask.getOldArchive(ArtifactJapicmpTask.groovy:33)
    at me.champeau.gradle.ArtifactJapicmpTask_Decorated.getOldArchive(Unknown Source)
    at me.champeau.gradle.JapicmpAbstractTask.exec(JapicmpAbstractTask.groovy:61)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 66 more
```

Files related to this `griffon-core` release are located at

https://bintray.com/griffon/griffon/griffon-core/2.0.0/view/files/org/codehaus/griffon/griffon-core/2.0.0

**Comment by lbergelson** [comment]
I encountered the same issue and this solved it for me.  Thank you.

**Comment by centic9** [comment]
I encountered the same, maybe this can be incorporated into the README?

**Comment by melix** [comment]
Closing as outdated: the new plugin works differently now, and this shouldn't be an issue anymore.
